import apiConfig from "@/content/public-api-config.json";

/**
 * The operations the docs are allowed to publish.
 *
 * `public-schema.graphql` is generated by walking every field of the backend's
 * `type Query` — there is no allowlist upstream, so schema membership says
 * nothing about whether an operation was ever meant for customers. The only
 * place that intent is recorded is the graphql-shield rule in
 * `mediajel-gql-service/src/webapp/middleware/permissions/index.ts`, and these
 * are the operations whose rule admits a public API token:
 *
 *   isAuthenticatedToken (13)  advertising core — an API key is explicitly allowed
 *   rules.isAuthenticated (13) accepts a dashboard user OR a public API token
 *   allow (6)                  deliberately open, no auth required
 *
 * Everything else in the generated schema is either `isDashboardEnabled` (107,
 * reachable only from a browser session — an API key can never satisfy it) or
 * absent from the rule map entirely (161, answered with no auth check at all).
 * Neither belongs in customer-facing docs. See issue #11568.
 *
 * Keep this list in sync with the shield map. Operations removed here can be
 * restored by adding them back once the backend opens them up.
 */
const CUSTOMER_FACING_QUERIES = [
  // isAuthenticatedToken — campaigns, orders, line items, orgs, tasks
  "campaign",
  "campaigns",
  "campaignsConnection",
  "campaignOrder",
  "campaignOrders",
  "campaignOrdersConnection",
  "lineItem",
  "lineItems",
  "lineItemsConnection",
  "org",
  "orgs",
  "orgsConnection",
  "tasksConnection",

  // rules.isAuthenticated — product / dispensary catalog
  "brand",
  "brands",
  "product",
  "products",
  "productsWithRecommendation",
  "catalog",
  "catalogItems",
  "reviews",
  "strain",
  "strains",
  "cannatypes",
  "getRecommendationValue",
  "getRecommendedProduct",

  // allow — public content, no authentication required
  "article",
  "articles",
  "articleCategory",
  "articleCategories",
  "regionGroups",
  "iABCategoryGroups",
] as const;

/**
 * Sign-in is unguarded by necessity — it is how a caller obtains the token every
 * other operation requires. Kept for that reason, not because it carries a rule.
 */
const PUBLIC_MUTATIONS = ["authSignIn"] as const;

export const PUBLIC_QUERY_NAMES: ReadonlySet<string> = new Set(
  CUSTOMER_FACING_QUERIES
);

export const PUBLIC_MUTATION_NAMES: ReadonlySet<string> = new Set(
  PUBLIC_MUTATIONS
);

export function isPublicOperation(
  name: string,
  type: "query" | "mutation"
): boolean {
  return type === "query"
    ? PUBLIC_QUERY_NAMES.has(name)
    : PUBLIC_MUTATION_NAMES.has(name);
}

/**
 * Category ids that still contain at least one published operation. 15 of the
 * 24 categories in the config document nothing a customer can call, so they are
 * dropped from the sidebar and the schema index rather than rendered empty.
 *
 * Derived from the config rather than hardcoded so that restoring an operation
 * brings its category back automatically.
 */
export function getPublicCategoryIds(): ReadonlySet<string> {
  const ids = new Set<string>();
  const { queries, mutations } = apiConfig.operations as {
    queries: Record<string, { category: string }>;
    mutations: Record<string, { category: string }>;
  };

  for (const [name, op] of Object.entries(queries)) {
    if (PUBLIC_QUERY_NAMES.has(name)) ids.add(op.category);
  }
  for (const [name, op] of Object.entries(mutations)) {
    if (PUBLIC_MUTATION_NAMES.has(name)) ids.add(op.category);
  }
  return ids;
}
